#!/usr/bin/env bash
#
# List imports from module.configurations at the top-most level
#
# Examples:
#
# ./list-imports homeManager.peach
#
# ./list-imports nixos.peach-asus

name="$1"
if [ -z $name ]; then
  echo "Expected 1 argument of configuration name" 1>&2
  exit 1
fi

script='
let
  inherit (builtins) elemAt;
  pkgs = import <nixpkgs> { };
  inherit (pkgs) lib;
  flake = (builtins.getFlake (builtins.toString ./.));
  configurations = flake.modules.configurations;
  accessImport = a: elemAt a.imports 0;
  module =
    (lib.pipe configurations."'"$name"'" [
      accessImport
      accessImport
      accessImport
    ]).module;
  imports = lib.lists.foldl (
    acc: x:
    if builtins.typeOf (elemAt x.imports 0) == "lambda" then
      acc ++ ((elemAt x.imports 0) { inherit pkgs; inherit lib; }).imports
    else
      acc ++ [ (elemAt (elemAt x.imports 0).imports 0)._file ]
  ) [ ] module.imports;
  importFiles = builtins.map (
    a:
    if builtins.typeOf a == "string" then
      a
    else if builtins.typeOf a == "path" then
      builtins.toString a
    else
      a._file
  ) imports;
  importNames = builtins.map (a: lib.lists.last (lib.splitString "#" a)) importFiles;
in
(builtins.concatStringsSep "\n" importNames) + "\n"
'

nix-instantiate --eval --expr "$script" --raw
